server:
  port: 8888

logging:
  path: logs
  file: ruleEngine.log

spring:
  application:
    name: ruleEngine
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kg.rule?serverTimezone=GMT
    username: root
    password: 123456

mybatis:
  type-aliases-package: com-greedy-ai.model
  mapper-locations:
    - mapper/*

neo4j:
  datasource:
    uri: bolt://localhost:7687
    username: neo4j
    password: 199915